# fly.toml app configuration file generated for jb3ail-qualify-ai-telephone on 2026-03-27T22:23:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jb3ail-qualify-ai-telephone'
primary_region = 'jnb'

[build]

[env]
  NODE_ENV = "production"
  DOMAIN = "jb3ail-qualify-ai-telephone.fly.dev"

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/api/health"
    timeout = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
